---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: {{ .Values.etcd.name }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.etcd.name }}
    app.kubernetes.io/instance: {{ .Values.etcd.name }}
    app.kubernetes.io/version: {{ (split ":" .Values.etcd.image)._1 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.etcd.name }}
spec:
  ports:
    - name: "listen-client-port"
      port: {{ .Values.etcd.service.port }}
      targetPort: {{ .Values.etcd.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.etcd.name }}
    app.kubernetes.io/instance: {{ .Values.etcd.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: {{ .Values.minio.name }}-{{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Values.minio.name }}
    app.kubernetes.io/instance: {{ .Values.minio.name }}
    app.kubernetes.io/version: {{ (split ":" .Values.minio.image)._1 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.minio.name }}
spec:
  ports:
    - name: "console-port"
      port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consolePort }}
    - name: "service-port"
      port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.minio.name }}
    app.kubernetes.io/instance: {{ .Values.minio.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "milvus-vector-db.labels" . | nindent 4 }}
  name: {{ include "milvus-vector-db.fullname" . }}
spec:
  ports:
    - name: "grpc-port"
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
    - name: "restful-api-port"
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
  selector:
    {{- include "milvus-vector-db.selectorLabels" . | nindent 4 }}
